startScene: "/branches/test_dynamics.yaml"
window:
  title: "Hello from application settings"
  size:
    width: 1280
    height: 720
  hints:
    visible: No
    resizable: Yes
    decorated: Yes
    focused: Yes
    maximized: No